title: Iman Rahimi
description: Data Scientist • Decision Scientist • Machine Learning & Optimization
theme: minima

header_pages:
  - index.md
  - academic.md
  - industry.md
  - projects.md
  - Case Study.md
  - contact.md
