theme: jekyll-theme-orderedlist
title: Iman Rahimi
description: Data Scientist · Decision Scientist · Machine Learning & Optimization Specialist

header_pages:
  - academic.md
  - industry.md
  - projects.md
  - case-studies.md
  - contact.md
