title: Iman Rahimi
description: Data Scientist · Decision Scientist · Machine Learning & Optimization
google_site_verification: "VLcAL3kME8ihsumntYJbwUtVX7ysNzisZ-gCdC5DBs" 
theme: minima

header_pages:
  - academic.md
  - industry.md
  - projects.md
  - flagship-dss.md
  - contact.md
